FROM quay.io/jupyter/base-notebook:python-3.11

USER root

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install \
  build-essential pkg-config cmake ninja-build python3-dev \
  gfortran libopenblas-dev liblapack-dev \
  zlib1g-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev \
  libxml2-dev libxslt1-dev \
  libffi-dev libssl-dev \
  libsqlite3-dev libbz2-dev liblzma-dev \
  graphviz \
  libnccl2 libnccl-dev &&\
  apt-get clean && rm -rf /var/lib/apt/lists/*


COPY requirements.txt requirements.txt


RUN pip install --no-cache-dir --requirement requirements.txt && \
  fix-permissions "${CONDA_DIR}" && \
  fix-permissions "/home/${NB_USER}"

RUN rm requirements.txt

COPY prerun/ prerun/

RUN for i in prerun/*.py; do python "$i"; done && rm -rf prerun

USER ${NB_UID}

