FROM quay.io/jupyter/base-notebook:python-3.11

USER root



COPY requirements.txt requirements.txt


RUN pip install --no-cache-dir --requirement requirements.txt&& pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu  && \
  fix-permissions "${CONDA_DIR}" && \
  fix-permissions "/home/${NB_USER}"

RUN rm requirements.txt

COPY prerun/ prerun/

RUN for i in prerun/*.py; do python "$i"; done && rm -rf prerun

USER ${NB_UID}

